name: to_do_list_app
description: A simple to do list application.
version: 0.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

